### PR TITLE
split Initial into Client Initial and Server Initial

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Comment by kazuho** [comment]
I am not against splitting Initial into two, however I am strictly opposed to splitting it to Client Initial and Server Initial.

Currently, there are four occasions where the Initial packet is sent: 1st CH, 1st SH (incl. HRR), 2nd CH, 2nd SH.

Considering that the token field is only required for 1st CH, we should special case that case only. Not 1st CH **and 2nd CH**.

**Comment by marten-seemann** [comment]
That defeats the whole purpose of this. I want to be able to look at the packet type and decide if I need to handle this packet statelessly or if I do a connection map lookup. Therefore, the first and the second CH need to be the same packet type, and different from the packets sent by the server.

**Comment by kazuho** [comment]
> I want to be able to look at the packet type and decide if I need to handle this packet statelessly or if I do a connection map lookup.

Whether if the 2nd CH is stateless depends on how the server generates a stateless HRR (which is a special form of SH).

Considering the fact that we have moved address validation out of TLS, I do not think that we would be using stateless HRR.

In other words, HRR and 2nd SH will be exchanged statefully, when there is a named group mismatch.

**Comment by ekr** [comment]
At this point I would prefer to leave this as an open issue to be handled by the WG

**Comment by marten-seemann** [comment]
Right. I missed the HRR.

**Pull request closed without merging**
